#!/bin/zsh
#
# configure-build.sh - Configure the XNU kernel build system
# Sets up all necessary environment variables and build directories
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_ROOT/BUILD_CONFIG.env"
SOURCES_DIR="$PROJECT_ROOT/sources"
BUILD_DIR="$PROJECT_ROOT/build"

# Source configuration
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: BUILD_CONFIG.env not found. Run ./scripts/detect-env.sh first"
    exit 1
fi
source "$CONFIG_FILE"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== XNU Kernel Build Configuration ===${NC}\n"

# Verify sources exist
if [[ ! -d "$SOURCES_DIR/xnu" ]]; then
    echo -e "${RED}ERROR: XNU sources not found at $SOURCES_DIR/xnu${NC}"
    echo "Run ./scripts/fetch-sources.sh first"
    exit 1
fi

echo -e "${BLUE}[1/4] Creating build directory structure...${NC}"

# Create architecture-specific build directories
for arch in $TARGET_ARCHS; do
    build_path="$BUILD_DIR/$arch"
    mkdir -p "$build_path"/{objects,intermediates,products}
    echo -e "${GREEN}✓${NC}  $arch build directory created"
done

echo -e "\n${BLUE}[2/4] Configuring XNU build environment...${NC}"

# Create build configuration file for make
cat > "$BUILD_DIR/BuildConfig.mk" << EOF
# XNU Kernel Build Configuration
# Auto-generated by configure-build.sh

# Paths
PROJECT_ROOT := $PROJECT_ROOT
SOURCES_DIR := $SOURCES_DIR
BUILD_DIR := $BUILD_DIR
OUTPUT_DIR := $PROJECT_ROOT/output
SDK_PATH := $SDK_PATH

# Architecture configuration
SUPPORTED_ARCHS := arm64 x86_64
TARGET_ARCHS := $TARGET_ARCH
NATIVE_ARCH := $NATIVE_ARCH

# Compiler configuration
CC := $XCODE_PATH/usr/bin/clang
CXX := $XCODE_PATH/usr/bin/clang++
LD := $XCODE_PATH/usr/bin/ld
AR := $XCODE_PATH/usr/bin/ar
RANLIB := $XCODE_PATH/usr/bin/ranlib
LIBTOOL := $XCODE_PATH/usr/bin/libtool
STRIP := $XCODE_PATH/usr/bin/strip

# SDK configuration
SDK_PATH := $SDK_PATH
MACOSX_DEPLOYMENT_TARGET := $MACOS_VERSION

# Compiler flags
COMMON_CFLAGS := -isysroot \$(SDK_PATH) -Wall -Wextra -fPIC
DEBUG_CFLAGS := -g -O0 -DDEBUG=1
RELEASE_CFLAGS := -O2 -DRELEASE=1

ifeq (\$(CONFIGURATION), Debug)
  CFLAGS := \$(COMMON_CFLAGS) \$(DEBUG_CFLAGS)
else
  CFLAGS := \$(COMMON_CFLAGS) \$(RELEASE_CFLAGS)
endif

CFLAGS += -DKERNEL -DKERNEL_PRIVATE -DKEYSONLY

# Linker flags
LDFLAGS := -isysroot \$(SDK_PATH)
ifeq (\$(BUILD_LTO), 1)
  LDFLAGS += -flto
  CFLAGS += -flto=thin
endif

# Optional features
BUILD_LTO := $LTO_SUPPORT
BUILD_KASAN := 0
BUILD_DEBUG := 1
VERBOSE := 1

# Build output control
ifeq (\$(VERBOSE), 1)
  VERBOSE_MAKE :=
else
  VERBOSE_MAKE := @
endif

# Kernel build settings
KERNEL_FRAMEWORK := Kernel
IOK_FRAMEWORK := IOKit
KERN_FRAMEWORK := kern
BSD_FRAMEWORK := bsd

EOF

echo -e "${GREEN}✓${NC}  Build configuration created"

echo -e "\n${BLUE}[3/4] Generating kernel build rules...${NC}"

# Create main kernel Makefile
cat > "$BUILD_DIR/Makefile.kernel" << 'EOF'
# Master Kernel Build Makefile

include BuildConfig.mk

# Kernel targets
XNU_KERNEL := kernel
XNU_KERNELCACHE := kernelcache
XNU_DSYM := kernel.dSYM

# Source directories
MACH_DIR := $(SOURCES_DIR)/xnu/osfmk
BSD_DIR := $(SOURCES_DIR)/xnu/bsd
IOKIT_DIR := $(SOURCES_DIR)/xnu/iokit
LIBKERN_DIR := $(SOURCES_DIR)/libkern
LIBSA_DIR := $(SOURCES_DIR)/xnu/libsa

# Architecture-specific directories
ifeq ($(TARGET_ARCHS), arm64)
  ARCH_DIR := $(MACH_DIR)/arm
else ifeq ($(TARGET_ARCHS), x86_64)
  ARCH_DIR := $(MACH_DIR)/i386
endif

# Build output
BUILD_ARCH_DIR := $(BUILD_DIR)/$(TARGET_ARCHS)
OBJ_DIR := $(BUILD_ARCH_DIR)/objects
PRODUCTS_DIR := $(BUILD_ARCH_DIR)/products
OUTPUT_KERNEL := $(OUTPUT_DIR)/$(TARGET_ARCHS)/kernel

# Source files (simplified - actual build would need complete list)
LIBKERN_SRCS := $(wildcard $(LIBKERN_DIR)/c++/*.cpp)
LIBSA_SRCS := $(wildcard $(LIBSA_DIR)/*.c)
MACH_SRCS := $(wildcard $(MACH_DIR)/kern/*.c) $(wildcard $(ARCH_DIR)/*.c)
BSD_SRCS := $(wildcard $(BSD_DIR)/kern/*.c) $(wildcard $(BSD_DIR)/bsd/*.c)
IOKIT_SRCS := $(wildcard $(IOKIT_DIR)/Kernel/*.cpp)

# Object files
LIBKERN_OBJS := $(patsubst %.cpp, $(OBJ_DIR)/libkern_%.o, $(notdir $(LIBKERN_SRCS)))
LIBSA_OBJS := $(patsubst %.c, $(OBJ_DIR)/libsa_%.o, $(notdir $(LIBSA_SRCS)))
MACH_OBJS := $(patsubst %.c, $(OBJ_DIR)/mach_%.o, $(notdir $(MACH_SRCS)))
BSD_OBJS := $(patsubst %.c, $(OBJ_DIR)/bsd_%.o, $(notdir $(BSD_SRCS)))
IOKIT_OBJS := $(patsubst %.cpp, $(OBJ_DIR)/iokit_%.o, $(notdir $(IOKIT_SRCS)))

ALL_OBJS := $(LIBKERN_OBJS) $(LIBSA_OBJS) $(MACH_OBJS) $(BSD_OBJS) $(IOKIT_OBJS)

# Compiler flags
CFLAGS := -fno-builtin -fno-common -fno-strict-aliasing
CFLAGS += -isysroot $(SDK_PATH)
CFLAGS += -I$(SOURCES_DIR)/xnu/osfmk
CFLAGS += -I$(SOURCES_DIR)/xnu/bsd
CFLAGS += -I$(SOURCES_DIR)/xnu/iokit/Kernel
CFLAGS += -I$(SOURCES_DIR)/libkern/include
CFLAGS += -DKERNEL -DKERNEL_PRIVATE -DKEYSONLY

ifeq ($(TARGET_ARCHS), arm64)
  CFLAGS += -arch arm64 -mmacosx-version-min=11.0
else ifeq ($(TARGET_ARCHS), x86_64)
  CFLAGS += -arch x86_64 -mmacosx-version-min=11.0
endif

ifeq ($(CONFIGURATION), Debug)
  CFLAGS += -g -O0 -DDEBUG=1
else
  CFLAGS += -O2 -DRELEASE=1
endif

# Targets
.PHONY: all clean kernel kernel-debug kernel-release

all: $(OUTPUT_KERNEL)

kernel: all

kernel-debug:
	@echo "Building kernel (Debug)"
	$(MAKE) all CONFIGURATION=Debug

kernel-release:
	@echo "Building kernel (Release)"
	$(MAKE) all CONFIGURATION=Release

$(OBJ_DIR):
	mkdir -p $@

$(PRODUCTS_DIR):
	mkdir -p $@

# Compile C source files
$(OBJ_DIR)/%.o: $(SOURCES_DIR)/xnu/osfmk/*/%.c | $(OBJ_DIR)
	$(VERBOSE_MAKE)$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(SOURCES_DIR)/xnu/bsd/*/%.c | $(OBJ_DIR)
	$(VERBOSE_MAKE)$(CC) $(CFLAGS) -c $< -o $@

# Compile C++ source files
$(OBJ_DIR)/%.o: $(SOURCES_DIR)/libkern/c++/%.cpp | $(OBJ_DIR)
	$(VERBOSE_MAKE)$(CXX) $(CFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(SOURCES_DIR)/xnu/iokit/*/%.cpp | $(OBJ_DIR)
	$(VERBOSE_MAKE)$(CXX) $(CFLAGS) -c $< -o $@

# Link kernel
$(OUTPUT_KERNEL): $(ALL_OBJS) | $(PRODUCTS_DIR)
	@echo "Linking kernel..."
	@mkdir -p $(OUTPUT_DIR)/$(TARGET_ARCHS)
	$(VERBOSE_MAKE)$(LD) $(LDFLAGS) -e _start -static -o $@ $(ALL_OBJS) -L$(SDK_PATH)/usr/lib -lSystem
	@echo "Generating debug symbols..."
	$(VERBOSE_MAKE)dsymutil $@ -o $@.dSYM
	@echo "Creating kernelcache..."
	$(VERBOSE_MAKE)gzip -c $@ > $(OUTPUT_DIR)/$(TARGET_ARCHS)/kernelcache
	@echo "✓ Kernel build complete: $@"

clean:
	@echo "Cleaning build directory..."
	rm -rf $(BUILD_ARCH_DIR)
	rm -rf $(OUTPUT_DIR)

help:
	@echo "XNU Kernel Build Targets:"
	@echo "  make all              - Build kernel (current config)"
	@echo "  make kernel-debug     - Build debug kernel"
	@echo "  make kernel-release   - Build optimized kernel"
	@echo "  make clean            - Remove all build products"

EOF

echo -e "${GREEN}✓${NC}  Kernel build rules generated"

echo -e "\n${BLUE}[4/4] Creating build helpers...${NC}"

# Create script to display build info
cat > "$BUILD_DIR/build-info.sh" << 'EOF'
#!/bin/zsh
# Display XNU build configuration

source BuildConfig.mk

echo "=== XNU Kernel Build Configuration ==="
echo ""
echo "Paths:"
echo "  Project Root:    $PROJECT_ROOT"
echo "  Sources:         $SOURCES_DIR"
echo "  Build Directory: $BUILD_DIR"
echo "  Output:          $OUTPUT_DIR"
echo ""
echo "Architecture:"
echo "  System Arch:     $NATIVE_ARCH"
echo "  Build Target:    $TARGET_ARCHS"
echo ""
echo "Toolchain:"
echo "  Compiler:        $CC"
echo "  SDK Path:        $SDK_PATH"
echo "  Deployment:      $MACOSX_DEPLOYMENT_TARGET"
echo ""
echo "Build Options:"
echo "  Configuration:   $CONFIGURATION"
echo "  LTO:             $([ $BUILD_LTO -eq 1 ] && echo "Enabled" || echo "Disabled")"
echo "  KASAN:           $([ $BUILD_KASAN -eq 1 ] && echo "Enabled" || echo "Disabled")"
echo "  Debug Symbols:   $([ $BUILD_DEBUG -eq 1 ] && echo "Yes" || echo "No")"

EOF

chmod +x "$BUILD_DIR/build-info.sh"
echo -e "${GREEN}✓${NC}  Build helpers created"

# Final summary
echo -e "\n${BLUE}=== Build Configuration Summary ===${NC}\n"

echo "Architecture:        $TARGET_ARCH"
echo "macOS Version:       $MACOS_VERSION"
echo "SDK Path:            $SDK_PATH"
echo "Build Directory:     $BUILD_DIR"
echo ""

echo -e "${GREEN}✓ Configuration complete${NC}"
echo ""
echo "Next steps:"
echo "  1. Review config:  ${YELLOW}cat $BUILD_DIR/BuildConfig.mk${NC}"
echo "  2. View details:   ${YELLOW}$BUILD_DIR/build-info.sh${NC}"
echo "  3. Build kernel:   ${YELLOW}./scripts/build-kernel.sh${NC}"
