#!/bin/bash
#
# detect-env.sh - Detect and verify build environment for XNU kernel compilation
# This script checks for all required tools and generates BUILD_CONFIG.env
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_ROOT/BUILD_CONFIG.env"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Darwin/XNU Build Environment Detection ===${NC}\n"

# Initialize config file
cat > "$CONFIG_FILE" << 'EOF'
# AUTO-GENERATED BUILD CONFIGURATION
# This file was generated by detect-env.sh

EOF

# 1. Detect macOS version
echo -e "${BLUE}[1/8] Detecting macOS version...${NC}"
MACOS_VERSION=$(sw_vers -productVersion)
MACOS_BUILD=$(sw_vers -buildVersion)
echo "macOS $MACOS_VERSION (Build $MACOS_BUILD)"
echo "export MACOS_VERSION=\"$MACOS_VERSION\"" >> "$CONFIG_FILE"
echo "export MACOS_BUILD=\"$MACOS_BUILD\"" >> "$CONFIG_FILE"

# Verify minimum macOS version (10.13+)
MIN_VERSION="11.0"
if [[ $(printf '%s\n' "$MIN_VERSION" "$MACOS_VERSION" | sort -V | head -n1) == "$MIN_VERSION" ]]; then
    echo -e "${GREEN}✓ Minimum macOS version requirement met${NC}"
else
    echo -e "${RED}✗ macOS $MACOS_VERSION is too old (minimum: $MIN_VERSION)${NC}"
    exit 1
fi

# 2. Detect system architecture
echo -e "\n${BLUE}[2/8] Detecting system architecture...${NC}"
SYSTEM_ARCH=$(uname -m)
echo "System Architecture: $SYSTEM_ARCH"
echo "export SYSTEM_ARCH=\"$SYSTEM_ARCH\"" >> "$CONFIG_FILE"

# Set build architecture based on system
if [[ "$SYSTEM_ARCH" == "arm64" ]]; then
    BUILD_ARCH="arm64"
    NATIVE_ARCH="arm64"
    echo -e "${GREEN}✓ Apple Silicon (ARM64) detected${NC}"
elif [[ "$SYSTEM_ARCH" == "x86_64" ]]; then
    BUILD_ARCH="x86_64"
    NATIVE_ARCH="x86_64"
    echo -e "${GREEN}✓ Intel (x86_64) detected${NC}"
else
    echo -e "${RED}✗ Unsupported architecture: $SYSTEM_ARCH${NC}"
    exit 1
fi

echo "export NATIVE_ARCH=\"$NATIVE_ARCH\"" >> "$CONFIG_FILE"
echo "export BUILD_ARCH=\"$BUILD_ARCH\"" >> "$CONFIG_FILE"

# 3. Find Xcode Command Line Tools
echo -e "\n${BLUE}[3/8] Locating Xcode Command Line Tools...${NC}"
XCODE_PATH=$(xcode-select -p 2>/dev/null || echo "")

if [[ -z "$XCODE_PATH" ]]; then
    echo -e "${RED}✗ Xcode Command Line Tools not found${NC}"
    echo -e "Install with: ${YELLOW}xcode-select --install${NC}"
    exit 1
fi

echo "Xcode Path: $XCODE_PATH"
echo -e "${GREEN}✓ Xcode Command Line Tools found${NC}"
echo "export XCODE_PATH=\"$XCODE_PATH\"" >> "$CONFIG_FILE"

# 4. Check Xcode version
echo -e "\n${BLUE}[4/8] Checking Xcode version...${NC}"
XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
CLANG_VERSION=$($XCODE_PATH/usr/bin/clang --version 2>/dev/null | head -1)

echo "$XCODE_VERSION"
echo "$CLANG_VERSION"
echo "export XCODE_VERSION=\"$XCODE_VERSION\"" >> "$CONFIG_FILE"
echo -e "${GREEN}✓ Xcode version detected${NC}"

# 5. Locate macOS SDK
echo -e "\n${BLUE}[5/8] Locating macOS SDK...${NC}"

# Try Command Line Tools path first
SDK_PATH="$XCODE_PATH/SDKs/MacOSX.sdk"

if [[ ! -d "$SDK_PATH" ]]; then
    # Try standard locations
    for path in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk; do
        if [[ -d "$path" ]]; then
            SDK_PATH="$path"
            break
        fi
    done
fi

if [[ ! -d "$SDK_PATH" ]]; then
    echo -e "${RED}✗ macOS SDK not found${NC}"
    exit 1
fi

# Get SDK version (optional - may hang on some systems)
SDK_VERSION="unknown"
SDK_BUILD="unknown"

echo "SDK Path: $SDK_PATH"
echo "SDK Version: $SDK_VERSION"
echo -e "${GREEN}✓ macOS SDK found${NC}"
echo "export SDK_PATH=\"$SDK_PATH\"" >> "$CONFIG_FILE"
echo "export SDK_VERSION=\"$SDK_VERSION\"" >> "$CONFIG_FILE"

# 6. Check required build tools
echo -e "\n${BLUE}[6/8] Checking required build tools...${NC}"

# Check each tool (POSIX-compatible, no arrays)
MISSING=""
MISSING_OPT=""

for tool in clang make python3 git dsymutil nm otool; do
    TOOL_PATH=""
    # Try command -v first
    if command -v "$tool" &> /dev/null; then
        TOOL_PATH=$(command -v "$tool" 2>/dev/null)
    fi
    # Fall back to xcrun for Xcode tools
    if [ -z "$TOOL_PATH" ]; then
        TOOL_PATH=$(xcrun -f "$tool" 2>/dev/null || true)
    fi
    
    if [ -n "$TOOL_PATH" ]; then
        echo -e "${GREEN}✓${NC} $tool: $TOOL_PATH"
    else
        echo -e "${RED}✗${NC} $tool: NOT FOUND"
        MISSING="$MISSING $tool"
    fi
done

for tool in llvm-config llvm-dis llvm-objdump; do
    TOOL_PATH=""
    if command -v "$tool" &> /dev/null; then
        TOOL_PATH=$(command -v "$tool" 2>/dev/null)
    fi
    if [ -z "$TOOL_PATH" ] && [ -f "/opt/homebrew/opt/llvm/bin/$tool" ]; then
        TOOL_PATH="/opt/homebrew/opt/llvm/bin/$tool"
    fi
    
    if [ -n "$TOOL_PATH" ]; then
        echo -e "${GREEN}✓${NC} $tool (optional): $TOOL_PATH"
    else
        echo -e "${YELLOW}⚠${NC} $tool (optional): NOT FOUND"
        MISSING_OPT="$MISSING_OPT $tool"
    fi
done

if [ -n "$MISSING" ]; then
    echo -e "\n${RED}Missing required tools:$MISSING${NC}"
    echo "Install Xcode Command Line Tools:"
    echo -e "  ${YELLOW}xcode-select --install${NC}"
    exit 1
fi

if [ -n "$MISSING_OPT" ]; then
    echo -e "\n${YELLOW}Warning: Some optional tools missing:$MISSING_OPT${NC}"
fi

# 7. Detect compiler capabilities
echo -e "\n${BLUE}[7/8] Detecting compiler capabilities...${NC}"

# Check for LTO support
if $XCODE_PATH/usr/bin/clang -flto -c -x c /dev/null -o /tmp/test_lto.o &>/dev/null; then
    echo -e "${GREEN}✓${NC} LTO (Link-Time Optimization) supported"
    LTO_SUPPORT=1
    rm -f /tmp/test_lto.o
else
    echo -e "${YELLOW}⚠${NC} LTO not supported"
    LTO_SUPPORT=0
fi

# Check for KASAN support
if $XCODE_PATH/usr/bin/clang -fsanitize=kernel-address -c -x c /dev/null -o /tmp/test_kasan.o &>/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} KASAN (Kernel Address Sanitizer) supported"
    KASAN_SUPPORT=1
    rm -f /tmp/test_kasan.o
else
    echo -e "${YELLOW}⚠${NC} KASAN not supported"
    KASAN_SUPPORT=0
fi

echo "export LTO_SUPPORT=$LTO_SUPPORT" >> "$CONFIG_FILE"
echo "export KASAN_SUPPORT=$KASAN_SUPPORT" >> "$CONFIG_FILE"

# 8. Generate final configuration
echo -e "\n${BLUE}[8/8] Generating build configuration...${NC}"

cat >> "$CONFIG_FILE" << EOF

# Build Paths
export PROJECT_ROOT="$PROJECT_ROOT"
export SOURCES_DIR="\$PROJECT_ROOT/sources"
export BUILD_DIR="\$PROJECT_ROOT/build"
export OUTPUT_DIR="\$PROJECT_ROOT/output"
export SCRIPTS_DIR="\$PROJECT_ROOT/scripts"

# Compiler and tools
export CC="$XCODE_PATH/usr/bin/clang"
export CXX="$XCODE_PATH/usr/bin/clang++"
export LD="$XCODE_PATH/usr/bin/ld"
export MAKE="/usr/bin/make"
export PYTHON3="$(which python3)"

# Build configuration
export CONFIGURATION=Debug
export VERBOSE=1
export BUILD_DEBUG=1
export BUILD_LTO=$LTO_SUPPORT
export BUILD_KASAN=0

# Kernel targets (can be modified as needed)
export TARGET_ARCHS="$BUILD_ARCH"
export SUPPORTED_ARCHS="arm64 x86_64"

# Optional components
export BUILD_DRIVERKIT=1
export BUILD_KEXTS=1
export BUILD_TOOLS=1

# Optimization level (for Release builds)
export OPTIMIZATION_LEVEL="-O2"

# Additional flags
export LDFLAGS="-isysroot $SDK_PATH"
export CFLAGS="-isysroot $SDK_PATH -I$SDK_PATH/usr/include"
export CXXFLAGS="-isysroot $SDK_PATH -I$SDK_PATH/usr/include"

EOF

# Print summary
echo -e "\n${BLUE}=== Environment Detection Summary ===${NC}\n"
echo "macOS Version:        $MACOS_VERSION"
echo "System Architecture:  $SYSTEM_ARCH"
echo "Build Architecture:   $BUILD_ARCH"
echo "Xcode Path:           $XCODE_PATH"
echo "SDK Path:             $SDK_PATH"
echo "SDK Version:          $SDK_VERSION"
echo ""
echo "LTO Support:          $([ $LTO_SUPPORT -eq 1 ] && echo "Yes" || echo "No")"
echo "KASAN Support:        $([ $KASAN_SUPPORT -eq 1 ] && echo "Yes" || echo "No")"
echo ""
echo -e "${GREEN}✓ Configuration saved to: $CONFIG_FILE${NC}"

# Verify configuration file
if [[ -f "$CONFIG_FILE" ]]; then
    echo -e "${GREEN}✓ Build environment detected successfully${NC}\n"
    echo "Next steps:"
    echo "  1. Review configuration: ${YELLOW}cat $CONFIG_FILE${NC}"
    echo "  2. Fetch sources:       ${YELLOW}./scripts/fetch-sources.sh${NC}"
    echo "  3. Configure build:     ${YELLOW}./scripts/configure-build.sh${NC}"
    echo "  4. Build kernel:        ${YELLOW}./scripts/build-kernel.sh${NC}"
else
    echo -e "${RED}✗ Failed to create configuration file${NC}"
    exit 1
fi
